name: clean_architecture_template
description: A Flutter project template based on clean architecture.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #view
  mask_text_input_formatter: ^2.4.0
  url_launcher: ^6.1.7
  badges: ^3.0.2
  flutter_app_badger: ^1.5.0
  flutter_svg: ^2.0.5
  bot_toast: ^4.1.3

  #logic
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  rxdart: ^0.28.0
  flutter_keyboard_visibility: ^6.0.0

  #rest
  dio: ^5.1.1
  http_parser: ^4.0.2

  #storage
  shared_preferences: ^2.0.15

  #config
  easy_localization: ^3.0.1
  easy_localization_loader: ^2.0.2
  responsive_sizer: ^3.1.1
  flutter_native_splash: ^2.2.13
  enum_to_string: ^2.0.1
  fimber: ^0.7.0
  pretty_dio_logger: ^1.1.1
  build_runner: ^2.3.2
  flutter_native_timezone: ^2.0.0
  internet_connection_checker: ^3.0.1
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.14.3
  intl: ^0.19.0
  draggable_fab: ^0.1.4
  wave: ^0.2.2
  expand_tap_area: ^1.1.1
  web_socket_channel: ^2.4.0
  web_socket_client: ^0.2.0
  ioc_container: ^1.0.12
  flutter_ioc_container: ^1.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  test: ^1.24.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/png/
    - assets/icons/svg/
    - assets/translations/
    - fonts/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
    - family: Nunito Sans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: fonts/NunitoSans-Bold.ttf
          weight: 700
