# Generated by Django 4.2.20 on 2025-04-27 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('easy', 'Легко'), ('medium', 'Середньо'), ('hard', 'Складно')], max_length=10)),
                ('hint', models.TextField(blank=True)),
                ('clue', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('single', 'Single-choice'), ('blank', 'Fill-in-the-blank'), ('order', 'Code ordering'), ('trace', 'Code tracing'), ('debug', 'Debugging')], max_length=10)),
                ('prompt', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.test')),
            ],
        ),
    ]
