# Generated by Django 4.2.20 on 2025-04-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_language_userprogress_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='clue',
        ),
        migrations.RemoveField(
            model_name='test',
            name='hint',
        ),
        migrations.AddField(
            model_name='question',
            name='clue',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True),
        ),
    ]
